### ISSUE TITLE
Need some help to compile on OSX 10.6.8

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#76]
I try to compile MLV App for OSX 10.6.8 Snow Leopard using Qt 5.1.1... there are many incompatibilies. Many I can comment out (with feature loss) for now, but here I have a problem now:
Compiler tells in many files, e.g. dualIso.c, dng.c, llrawproc.c,...:
struct raw_info has no member named active_area
Do you have an idea why?!

**Comment by bouncyball-git** [comment]
I'll take a look looks like something in raw.h

**Comment by masc4ii** [comment]
e.g. raw_info.pitch is known, but raw_info.active_area.x1 is not. Even the editor draws active_area black instead of darkred... no problem on my normal system.

**Comment by bouncyball-git** [comment]
`

    int32_t black_level;            // autodetected
    int32_t white_level;            // somewhere around 13000 - 16000, varies with camera, settings etc
                                    // would be best to autodetect it, but we can't do this reliably yet
    union                           // DNG JPEG info
    {
        struct
        {
            int32_t x, y;           // DNG JPEG top left corner
            int32_t width, height;  // DNG JPEG size
        } jpeg;
        struct
        {
            int32_t origin[2];
            int32_t size[2];
        } crop;
    };
    union                       // DNG active sensor area (Y1, X1, Y2, X2)
    {
        struct
        {
            int32_t y1, x1, y2, x2;
        } active_area;
        int32_t dng_active_area[4];
    };
    int32_t exposure_bias[2];       // DNG Exposure Bias (idk what's that)
    int32_t cfa_pattern;            // stick to 0x02010100 (RGBG) if you can
    int32_t calibration_illuminant1;
    int32_t color_matrix1[18];      // DNG Color Matrix
    int32_t dynamic_range;          // EV x100, from analyzing black level and noise (very close to DxO)
};
`

**Comment by bouncyball-git** [comment]
second union defines:

```
struct
    {
        int32_t y1, x1, y2, x2;
    } active_area;

```
or
   ` int32_t dng_active_area[4];`

**Comment by bouncyball-git** [comment]
Looks like clang version issue?

**Comment by bouncyball-git** [comment]
Maybe that union or/or weirdness misleads it :)

**Comment by masc4ii** [comment]
Clang on 10.9+ has no problem. It seems Qt on 10.6.8 uses GCC only. Maybe here is the problem... 
So what could I do to avoid? Delete the union? Does someone use dng_active_area?

**Comment by bouncyball-git** [comment]
Try to delete dng_activ_area. In dng.c only active_area is used.

**Comment by masc4ii** [comment]
Yes that works. But now I get the same problem with crop/jpeg union in raw_info. Why does this compiler not understand an union?!

**Comment by masc4ii** [comment]
When I search in the net, I think I need a different compiler... nice :-(

**Comment by bouncyball-git** [comment]
As I predicted ;)

**Comment by masc4ii** [comment]
Normaly I use Clang, here I have to use GCC. But I think I'll let it be. Would be nice to have the old MacBook in the next holiday and not the newer one... but that is too much work ;-)

**Comment by bouncyball-git** [comment]
I'm just curious - what version of GCC is that, which does not understand unions in the struct?

**Comment by masc4ii** [comment]
This version is included in XCode 3.2.6.

**Comment by bouncyball-git** [comment]
Try:
`xcrun gcc -v`

It have to be gcc 4.2 or something like this.

**Comment by masc4ii** [comment]
gcc version 4.2.1 (Apple Inc. build 5666) (dot 3)
