### ISSUE TITLE
1.9 Release

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#179]

**Comment by masc4ii** [comment]
I wanted to add the AVIR rescaling to ffmpeg before this release. But it seems more complicated than expected. Was watching startPipe() several times and just thought "uff". There is so much inside to think about when changing. I'll need some more time, but have only some days to release 1.9 bofore holiday. Would it be okay to change that for next release? If yes, I would be ready for 1.9.

**Comment by ilia3101** [comment]
Ok sure let's leave AVIR for ffmpeg until next release.

**Comment by masc4ii** [comment]
What about the default profile? Other little features until the release?

**Comment by ilia3101** [comment]
lets leave new default profile until next version as well.

**Comment by masc4ii** [comment]
@bouncyball-git : version tag is commited. Could you please compile Win64 version?

**Comment by masc4ii** [comment]
Compiling linux version was difficult on Ubuntu 14.04, because g++ was too old for c++14 needed by AVIR. Got installed g++5, now it compiles, but ffmpeg unpack and install commands do not work anymore for appimage. Did it manually now, but this needs to be fixed.

**Comment by bouncyball-git** [comment]
Yeah I will tomorrow OK? Have no my Linux dev machine right now.

**Comment by masc4ii** [comment]
No problem. Ah, you cross compile Win64 version always on linux, right!? 
My small linux problem has time... as I wrote, I did it somehow manually for now.

**Comment by bouncyball-git** [comment]
Hm... something is not right regarding ThreadPool.h

avir/ThreadPool.h:47:18: error: 'thread' is not a member of 'std'
     std::vector< std::thread > workers;

I'll have to figure out.

**Comment by masc4ii** [comment]
Could be the same problem I had yesterday on Linux. You need a c++14 capable compiler. I had to update to g++ v5 to make it work.

**Comment by bouncyball-git** [comment]
I'm using v5.4.0 :(

**Comment by masc4ii** [comment]
Here on Windows it compiles with MinGW 7.3.0 and Qt 5.13.1. If you have no success, I could post the Win64 dynamic version.
P.S.: I hate this "workers thread" solution. Got already grey hair with that. But it is the only way we get AVIR multithreaded.

**Comment by bouncyball-git** [comment]
I will try latest versions too. Meanwhile you post the dynamic version and I will add static later after successfull compilation (hopefully) :)

**Comment by bouncyball-git** [comment]
Phew! Finally it compiled with g++ 7.4 :D. Uploaded.

**Comment by masc4ii** [comment]
Jippi. Hopefully it works better than my dynamic build. Seems to make problems for some guys...
With this compiler it worked out of the box? Or did you have more problems to solve?

**Comment by bouncyball-git** [comment]
With 7.4.0 toolchain it worked out of the box!

**Comment by bouncyball-git** [comment]
Hey guys

1. The profile preset combobox does not not show current/selected preset name (always shows Select Preset...). Is that normal behavior? Or just Linux version behaves this incorrect way?
2. How AVIR is implemented? All resize methods in export dialog now runs AVIR code instead of ffmpeg?

**Comment by masc4ii** [comment]
1. Yes, this is correct behavior. It makes no sense to show the selected item, because the user can change the sub settings.

2. AVIR is always used on AVFoundation export and on Single Frame Export (PNG), as well for the viewer if "Better resizer for viewer" is enabled. Otherwise ffmpeg or the DNG metadata is used for rescaling.

**Comment by bouncyball-git** [comment]
1. Ah OK. I would prefer to have preset name shown until sub setting is changed. If changed show name "Custom". This would be more intuitive :) But never mind...
2. I need to get back my MacBook Pro from my daughter!!! ;)

**Comment by masc4ii** [comment]
1. Yes, me/us too. But this would have been 3x more difficult. Had it like that before but did not get it bug free / 100% working.
2. v1.10 will have AVIR also for ffmpeg export. But this is a big change in ffmpeg pipe function.

**Comment by bouncyball-git** [comment]
Thanks for explanations.
